// GENERATED by scripts/build-senses.mjs — do not edit by hand.
// Source: WordNet 3.1 (Princeton) filtered by the OpenSubtitles-2018 English
// frequency list. Re-run the script to change it; see the header there for the
// depth and frequency thresholds and the anchors each list was grown from.
//
// Plain data, no dependency, nothing fetched: the scan stays instant and
// offline, exactly as it was when the lists were hand-written.

export interface Sense {
  label: string;
  /** Tailwind classes for the sense pill. */
  tw: string;
  /** Tailwind class for the highlight mark in the scanned text. */
  mark: string;
  /** Base forms belonging primarily to this sense. Hand-written entries come
   *  first — the hover tooltip shows the head of this list. Inflections live
   *  in the index below. */
  words: string[];
}

export const SENSES: Sense[] = [
  {
    label: "Sight",
    tw: "bg-amber-100 text-amber-800",
    mark: "bg-amber-200",
    words: ["see","look","glow","dark","bright","flash","shimmer","shine","shadow","blur","color","colour","light","haze","glare","flicker","gleam","pale","vivid","dim","sparkle","dazzle","reflect","silhouette","transparent","visible","glint","loom","watch","stare","gaze","peer","glimpse","spy","observe","notice","appear","fade","blaze","beam","ray","shade","tint","hue","cloud","sky","star","moon","sun","mist","fog","smoke","steam","dusk","dawn","twilight","sunlight","moonlight","daylight","lamplight","candlelight","firelight","reflection","outline","edge","rim","line","stripe","speck","fleck","blot","stain","mark","blemish","pattern","grain","white","black","grey","gray","blank","blanc","hollow","gap","dome","curve","ridge","groove","amber","apricot","aqua","beady","blackness","blazing","blinding","blue","brightness","brilliance","brown","burgundy","camouflaged","claret","colored","coloured","concealed","coral","crimson","crystalline","darkened","darkness","ebony","emerald","eye","fawn","fluorescent","flushed","glance","glaring","gleaming","glistening","glitter","glittering","gloom","gloomy","gold","golden","green","hidden","illuminated","invisibility","invisible","ivory","lighted","lit","livid","luminous","moonlit","navy","ogle","orange","pearl","pearly","peep","pink","purple","radiance","radiant","red","reddish","saffron","shape","sheen","shiny","silken","silver","silvery","sparkly","splendor","splendour","starlight","sunshine","tan","topaz","transparency","turquoise","twinkling","undetectable","unseen","violet","visibility","yellow"],
  },
  {
    label: "Sound",
    tw: "bg-blue-100 text-blue-800",
    mark: "bg-blue-200",
    words: ["hear","ring","echo","hum","whisper","creak","crash","bang","murmur","roar","silence","quiet","loud","hiss","buzz","clatter","thud","snap","rumble","groan","screech","drone","muffled","resonate","vibrate","tick","clang","rustle","howl","shriek","rattle","clap","knock","tap","ping","pop","crack","squeak","chirp","toll","chime","noise","song","note","tone","pitch","volume","whistle","sigh","gasp","footstep","voice","hush","din","racket","clink","thump","patter","drip","swish","crackle","whir","gurgle","boom","peal","wail","moan","yell","shout","mutter","mumble","laugh","cough","breath","bam","banging","bell","blare","blaring","blast","buzzing","chattering","clanging","clanking","clash","click","cluck","clucking","cracking","crackling","creaking","crow","crunch","deafening","drum","grinding","growl","grumble","grumbling","grunt","hissing","hubbub","humming","hushed","knocking","murmuring","muted","muttering","noisy","overhear","popping","rattling","ringing","roaring","rustling","scraping","scratching","scream","screeching","shattering","shouted","silent","sound","spatter","splash","splatter","sputtering","squeaking","squeaky","squeal","squealing","subdued","tapping","thumping","thunder","thunderclap","thundering","thunderous","thunk","ticking","tinkle","tinkling","trampling","uproar","whirring","whistling","yelled","yelping","zing"],
  },
  {
    label: "Smell",
    tw: "bg-emerald-100 text-emerald-800",
    mark: "bg-emerald-200",
    words: ["smell","scent","aroma","odor","odour","stale","fresh","musty","damp","sweet","sour","bitter","pungent","fragrance","reek","waft","acrid","smoky","earthy","rotten","perfume","incense","mildew","pine","petrichor","decay","tang","whiff","stench","sniff","inhale","exhale","mould","mold","rot","fume","vapour","vapor","nostril","breathe","stink","sooty","fusty","rancid","soapy","tarry","resin","sap","dung","sewage","ammonia","antiseptic","bleach","ozone","brackish","foul","fragrant","perfumed","scented","smelly","stinky"],
  },
  {
    label: "Taste",
    tw: "bg-rose-100 text-rose-800",
    mark: "bg-rose-200",
    words: ["taste","salty","savory","savoury","flavor","flavour","bland","rich","sharp","tangy","metallic","syrup","acid","dry","smooth","thick","thin","watery","chewy","crisp","raw","ripe","burnt","sugar","salt","spice","zest","mellow","tart","chalky","oily","creamy","tongue","lick","sip","gulp","swig","chew","bite","suck","mouthful","aftertaste","honey","lemon","vinegar","bread","butter","milk","cream","brine","yeast","tinny","fizzy","acidic","acidity","drink","eat","fruity","gobble","minty","nutty","savor","scrumptious","slurp","spicy","tasteless","tasty","yummy"],
  },
  {
    label: "Touch",
    tw: "bg-purple-100 text-purple-800",
    mark: "bg-purple-200",
    words: ["touch","feel","soft","rough","warm","cold","hard","dull","slick","sticky","wet","brittle","tender","pressure","grip","scratch","scrape","brush","stroke","rub","press","pinch","squeeze","grab","texture","surface","coarse","silky","gritty","numb","tingle","sting","prick","abrasive","bristle","fuzzy","velvety","jagged","slippery","cool","hot","chill","heat","freeze","frost","ice","burn","dusty","greasy","waxy","furry","woolly","prickly","clammy","tacky","glassy","polished","flat","flatness","solid","stone","rock","granite","marble","slate","wood","metal","glass","cloth","silk","velvet","wool","linen","leather","paper","sand","mud","clay","dust","grit","bevel","balm","cotton","denim","corduroy","tweed","gauze","lace","satin","burlap","rubber","plastic","tin","steel","iron","brass","copper","concrete","brick","tile","plaster","varnish","wax","foam","straw","bark","fur","feather","husk","rind","seam","rust","chalk","water","ash","dirt","soot","splinter","crumb","enamel","lacquer","arid","baked","blistering","bumpy","coolness","cracked","crushed","dank","dried","fiery","firm","fluffy","frigid","frosty","gravel","heated","humid","humidity","icy","limestone","moist","muddy","mushy","overheated","padded","parched","pointed","rocky","scorched","scorching","scratchy","sharpened","sizzling","softness","soggy","spiked","squishy","steaming","steamy","steely","stony","sultry","temperature","woody"],
  },
  {
    label: "Organic",
    tw: "bg-orange-100 text-orange-800",
    mark: "bg-orange-200",
    words: ["pulse","sweat","blood","heartbeat","heart","bone","skin","muscle","hunger","thirst","nausea","dizzy","ache","pain","tire","exhaust","shiver","tremble","flush","beat","lung","throat","stomach","gut","nerve","body","flesh","vein","artery","blink","swallow","choke","yawn","sneeze","cry","hand","arm","forearm","wrist","elbow","shoulder","knee","spine","rib","jaw","tooth","teeth","eyelid","fingertip","knuckle","palm","chest","belly","hip","thigh","shin","ankle","heel","sole","scalp","temple","cheek","brow","tear","spit","saliva","itch","cramp","clench","wince","flinch","shudder","faint","weary","tired","queasy","feverish","numbness","pang","throb","heave","retch","hiccup","snore","yelp","thumb","hair","nail","eyelash","eyebrow","beard","stubble","wrinkle","bruise","blister","callus","scab","freckle","pore","sinew","marrow","tendon","gristle","agony","brain","breast","chin","choking","coldness","colic","coughing","ear","face","fat","fatty","fever","finger","forehead","gum","head","headache","hurting","joint","lip","liver","lump","muscular","neck","pant","puff","scar","skeletal","skeleton","snort","stomachache","suffering","swelling","tissue","toe","toothache","waist","warmth"],
  },
  {
    label: "Kinesthetic",
    tw: "bg-teal-100 text-teal-800",
    mark: "bg-teal-200",
    words: ["move","walk","run","step","sway","drift","turn","spin","slide","glide","rush","crawl","float","fall","rise","sink","leap","jump","stagger","stumble","lurch","march","pace","wander","stand","sit","kneel","crouch","lean","balance","hover","hang","bend","curl","heavy","weightless","weight","gravity","lift","drop","carry","drag","haul","momentum","tension","pull","push","stretch","reach","resist","tilt","totter","teeter","perch","settle","slump","sprawl","recline","rest","tumble","roll","swing","tremor","jolt","judder","shift","steady","unsteady","upright","stiff","limp","slack","taut","loose","heaviness","lightness","poise","stance","posture","gesture","weigh","raise","lower","hoist","brace","prop","cradle","advance","approach","ascend","backtrack","barge","bending","bob","bounce","bouncy","budge","bustle","cascade","circle","climb","coil","creep","cross","dance","dart","dash","dawdle","deflect","depart","descend","deviate","dive","dodge","dribble","drive","duck","falter","flap","flip","flop","flounder","flow","flutter","fly","fumble","gallop","hasten","hitch","hop","hurry","hustle","inch","jerk","lightweight","limping","loop","lumber","lunge","motion","movement","overtake","overturn","pivot","plunge","pounce","pound","prance","prowl","quiver","race","rebound","recoil","reel","retreat","return","revolve","ride","ripple","roam","rotate","ruffle","scatter","scoot","scramble","scuff","shake","shimmy","shuffle","sidle","skim","skip","slink","slip","sneak","soar","spill","spiral","spring","squirm","stability","stabilized","stable","stamp","steal","stomp","streak","stream","stroll","strut","surge","swagger","swerve","swim","swirl","swivel","swoop","thrash","thrust","tight","tiptoe","topple","trail","tramp","trample","travel","traverse","tread","trembling","trickle","trip","twitch","twitching","veer","wade","wave","waver","wheel","whirl","wiggle","withdraw","wobble","wrench","wriggle","zigzag"],
  },
  {
    label: "Physical",
    tw: "bg-violet-100 text-violet-800",
    mark: "bg-violet-200",
    words: ["break","cut","dig","fold","hold","pour","throw","twist","wipe","crush","wring","knead","carve","chip","split","bind","tie","knot","stack","pile","sweep","scrub","polish","dent","peel","strip","stitch","weave","hammer","saw","dip","soak","rinse","wash","fill","empty","open","close","shut","lock","unlock","grind","scour","smear","spread","daub","plug","wedge","clamp","hook","latch","fasten","loosen","tighten","unscrew","screw","bolt","glue","paste","pin","staple","trim","clip","slice","chop","shred","mash","squash","flatten","crumple","crease","tuck","wrap","unwrap","bury","scoop","shovel","sift","strain","pump","stir","whisk","toss","fling","hurl","shove","nudge","prod","poke","rap","strike","hit","slap","punch","kick","buckle","bust","clinch","drill","gash","hack","lodge","notch","padlock","rip","sculpt","secure","sever","sew","slash","slit","stick","strap","wire","zip"],
  },
];

/**
 * Every inflected form the scan knows, grouped by primary sense — the groups
 * are in `SENSES` order, so a form's position *is* its primary sense and
 * nothing has to be repeated per entry.
 *
 * A word that belongs to more than one sense carries its secondaries after a
 * `>`: `light>6` is primarily Sight, secondarily Kinesthetic. The scanner
 * promotes a secondary only when the surrounding words support it — see
 * `lookupSense`/`scanText` in src/lib/text/senses.ts.
 */
const PACKED: string[] = [
  // Sight
  `
    amber amberer amberest amberly amberrer amberrest ambers appear appeared
    appearing appears apricot apricots aqua aquae aquas beadier beadiest
    beadily beady beam beamed beaming beams black blacked blacker blackest
    blacking blackly blackness blacknesses blacks blanc blancs blank blanked
    blanker blankest blanking blankly blanks blaze blazed blazes blazing
    blazingly blazings blemish blemished blemishes blemishing blinding
    blindingly blot bloted bloting blots blotted blotting blue blued bluely
    bluer blues bluest bluing blur blured bluring blurred blurring blurs
    bright brighter brightest brightly brightness brightnesses brilliance
    brilliances brown browned browner brownest browning brownly browns
    burgundies burgundy camouflaged camouflagedly candlelight candlelights
    claret clareted clareting clarets claretted claretting cloud clouded
    clouding clouds color colored coloredly colorer colorest coloring colorly
    colorred colorrer colorrest colorring colors colour coloured colouredly
    colourer colourest colouring colourly colours concealed concealedly coral
    corally corals crimson crimsoned crimsoner crimsonest crimsoning crimsonly
    crimsonned crimsonner crimsonnest crimsonning crimsons crystalline
    crystallinely curve>6 curved>6 curves>6 curving>6 dark darkened darkenedly
    darker darkest darkly darkness darknesses darks dawn dawned dawning dawns
    daylight daylights dazzle dazzled dazzles dazzling dim dimed dimer dimest
    diming dimly dimmed dimmer dimmest dimming dims dome domes dusk dusked
    dusking dusks ebonier ebonies eboniest ebonily ebony edge>46 edged>46
    edges>46 edging>46 emerald emeralds eye>5 eyed>5 eyes>5 eying>5 fade faded
    fades fading fawn fawned fawning fawns firelight firelights flash flashed
    flasher flashes flashest flashing flashly fleck flecked flecking flecks
    flicker>6 flickered>6 flickering>6 flickerred>6 flickerring>6 flickers>6
    fluorescent fluorescently fluorescents flushed flushedly fog foged fogged
    fogging foging fogs gap gaped gaping gapped gapping gaps gaze gazed gazes
    gazing glance glanced glances glancing glare glared glares glaring
    glaringly gleam gleamed gleaming gleamingly gleamings gleams glimpse
    glimpsed glimpses glimpsing glint glinted glinting glints glistening
    glisteningly glitter glittered glittering glitteringly glitterred
    glitterring glitters gloom gloomier gloomiest gloomily glooms gloomy glow
    glowed glowing glows gold golden goldener goldenest goldenly goldenner
    goldennest golder goldest goldly golds grain grained graining grains gray
    grayed grayer grayest graying grayly grays grayyer grayyest green greened
    greener greenest greening greenly greens grey greyed greyer greyest
    greying greyly greys greyyer greyyest groove grooved grooves grooving haze
    hazed hazes hazing hidden hiddener hiddenest hiddenly hiddenner hiddennest
    hollow hollowed hollower hollowest hollowing hollowly hollows hollowwer
    hollowwest hue hued hues huing illuminated illuminatedly invisibilities
    invisibility invisible invisibly ivories ivory lamplight lamplights
    light>6 lighted lightedly lighter>6 lightest>6 lighting>6 lightly>6
    lights>6 line lines lit litai liter litest litly lits litter littest livid
    lividder lividdest livider lividest lividly look looked looking looks loom
    loomed looming looms luminous luminously mark marked marking marks mist
    misted misting mists moon mooned mooning moonlight moonlighted
    moonlighting moonlights moonlit moonliter moonlitest moonlitly moonlitter
    moonlittest moons navies navy notice noticed notices noticing observe
    observed observes observing ogle ogled ogles ogling orange orangely
    oranger oranges orangest outline outlined outlines outlining pale paled
    palely paler pales palest paling pattern patterned patterning patterns
    pearl pearled pearlier pearlies pearliest pearlily pearling pearls pearly
    peep peeped peeping peeps peer peered peering peers pink pinked pinker
    pinkest pinking pinkly pinks purple purpled purpler purples purplest
    purpling purply radiance radiances radiant radiantly ray rayed raying rays
    red redded redder reddest redding reddish reddishly redly reds reflect
    reflected reflecting reflection reflections reflects ridge ridged ridges
    ridging rim rimed riming rimmed rimming rims saffron saffrons see seed
    seen sees seing shade shaded shades shading shadow>6 shadowed>6
    shadowing>6 shadows>6 shape shaped shapes shaping sheen sheens shimmer
    shimmered shimmering shimmerred shimmerring shimmers shine shined shines
    shinier shiniest shinily shining shiny shone silhouette silhouetted
    silhouettes silhouetting silken silkener silkenest silkenly silkenner
    silkennest silver silvered silverer silverest silverier silveriest
    silverily silvering silverly silverred silverrer silverrest silverring
    silvers silvery skied skies sky skying smoke smoked smokes smoking sparkle
    sparkled sparkles sparklier sparkliest sparklily sparkling sparkly speck
    specked specking specks spied spies splendor splendors splendour
    splendours spy spying stain stained staining stains star stare stared
    starer stares starest staring starlight starlights starly starred starrer
    starrest starring stars steam>6 steamed>6 steams>6 stripe striped stripes
    striping sun suned suning sunlight sunlights sunned sunning suns sunshine
    sunshines tan taned taner tanest taning tanly tanned tanner tannest
    tanning tans tint tinted tinting tints topaz topazes transparencies
    transparency transparent transparently turquoise turquoises twilight
    twilighter twilightest twilightly twilights twinkling twinklingly
    twinklings undetectable undetectably unseen unseener unseenest unseenly
    unseens violet violeter violetest violetly violets violetter violettest
    visibilities visibility visible visibler visiblest visibly vivid vividder
    vividdest vivider vividest vividly watch watched watches watching white
    whited whitely whiter whites whitest whiting yellow yellowed yellower
    yellowest yellowing yellowly yellows yellowwer yellowwest`,
  // Sound
  `
    bam bams bang banged banging bangingly bangings bangs bell belled belling
    bells blare blared blares blaring blaringly blarings blast blasted
    blasting blasts boom boomed booming booms breath>5 breaths>5 buzz>6
    buzzed>6 buzzes>6 buzzing buzzingly chattering chatterings chime chimed
    chimes chiming chirp chirped chirping chirps clang clanged clanging
    clangingly clangs clanking clankingly clap claped claping clapped clapping
    claps clash clashed clashes clashing clatter clattered clattering
    clatterred clatterring clatters click>6 clicked>6 clicking>6 clicks>6
    clink clinked clinking clinks cluck clucked clucking cluckings clucks
    cough>5 coughed>5 coughs>5 crack>7 cracker>7 crackest>7 cracking
    crackingly crackings crackle crackled crackler crackles cracklest
    crackling cracklings crackly cracks>7 crash>6 crashed>6 crashes>6
    crashing>6 creak creaked creaking creakings creaks crow crowed crowing
    crows crunch crunched crunches crunching deafening deafeningly din dined
    dining dinned dinning dins drip>6 driped>6 driping>6 dripped>6 dripping>6
    drips>6 drone droned drones droning drum drumed druming drummed drumming
    drums echo echoed echoes echoing echos footstep footsteps gasp>5 gasped>5
    gasping>5 gasps>5 grinding grindings groan groaned groaning groans growl
    growled growling growls grumble grumbled grumbles grumbling grumblingly
    grumblings grunt grunted grunting grunts gurgle gurgled gurgles gurgling
    hear heard heared hearing hears hiss hissed hisses hissing hissings howl
    howled howling howls hubbub hubbubs hum humed huming hummed humming
    hummings hums hush hushed hushedly hushes hushing knock>7 knocked>7
    knocking knockings knocks>7 laugh laughed laughing laughs loud louder
    loudest loudly moan moaned moaning moans muffled muffledly mumble mumbled
    mumbles mumbling murmur murmured murmuring murmuringly murmurings
    murmurred murmurring murmurs muted mutedly mutter muttered muttering
    mutterings mutterred mutterring mutters noise noised noises noisier
    noisiest noisily noising noisy note noted notes noting overhear overheard
    overheared overhearing overhears patter pattered pattering patterred
    patterring patters peal pealed pealing peals ping pinged pinging pings
    pitch>6 pitched>6 pitches>6 pitching>6 pop>7 poped>7 poper>7 popest>7
    poping>7 poply>7 popped>7 popper>7 poppest>7 popping poppings pops>7 quiet
    quieted quieter quietest quieting quietly quiets racket racketed racketing
    rackets racketted racketting rang rattle>6 rattled>6 rattles>6 rattling
    rattlingly rattlings resonate resonated resonates resonating ring ringed
    ringing ringings rings roar roared roaring roaringly roarings roars rumble
    rumbled rumbles rumbling rung rustle rustled rustles rustling rustlingly
    rustlings scraping scrapings scratching scratchings scream screamed
    screaming screams screech screeched screeches screeching screechings
    shattering shatteringly shatterings shout shouted shoutedly shouting
    shouts shriek shrieked shrieking shrieks sigh>5 sighed>5 sighing>5 sighs>5
    silence silenced silences silencing silent silently snap>7 snaped>7
    snaping>7 snapped>7 snapping>7 snaps>7 song songs sound sounded sounder
    soundest sounding soundly sounds spatter spattered spattering spatterred
    spatterring spatters splash>6 splashed>6 splashes>6 splashing>6 splatter
    splattered splattering splatterred splatterring splatters sputtering
    sputterings squeak squeaked squeakier squeakiest squeakily squeaking
    squeakingly squeaks squeaky squeal squealed squealing squealingly squeals
    subdued subduedly swish swished swishes swishing swishly tap>7 taped>7
    taping>7 tapped>7 tapping tappings taps>7 thud thudded thudding thuded
    thuding thuds thump>6 thumped>6 thumping thumpingly thumpings thumps>6
    thunder>6 thunderclap thunderclaps thundered>6 thundering thunderingly
    thunderous thunderously thunderred>6 thunderring>6 thunders>6 thunk thunks
    tick ticked ticking tickings ticks tinkle tinkled tinkles tinkling
    tinklingly toll tolled tolling tolls tone toned tones toning trampling
    tramplings uproar uproars vibrate>6 vibrated>6 vibrates>6 vibrating>6
    voice voiced voices voicing volume volumes wail wailed wailing wails whir
    whired whiring whirred whirring whirringly whirrings whirs whisper
    whispered whispering whisperred whisperring whispers whistle>6 whistled>6
    whistles>6 whistling whistlings yell yelled yelledly yelling yells yelping
    yelpings zing zings`,
  // Smell
  `
    acrid acridder acriddest acrider acridest acridly ammonia ammonias
    antiseptic antisepticly antiseptics aroma aromas bitter>3 bittered>3
    bitterer>3 bitterest>3 bittering>3 bitterly>3 bitterred>3 bitterrer>3
    bitterrest>3 bitterring>3 bitters>3 bleached bleaches bleaching brackish
    brackishly breathe>5 breathed>5 breathes>5 breathing>5 damp>4 damped>4
    damper>4 dampest>4 damping>4 damply>4 damps>4 decay decayed decaying
    decays dung dunged dunging dungs earthier earthiest earthily earthy
    exhale>5 exhaled>5 exhales>5 exhaling>5 foul fouled fouler foulest fouling
    foully fouls fragrance fragrances fragrant fragrantly fresh fresher
    freshest freshly fume fumed fumes fuming fustier fustiest fustily fusty
    incense incensed incenses incensing inhale>5 inhaled>5 inhales>5
    inhaling>5 mildew mildewed mildewing mildews mold molded molding molds
    mould moulded moulding moulds mustier mustiest mustily musty nostril
    nostrils odor odors odour odours ozone ozones perfume perfumed perfumedly
    perfumes perfuming petrichor petrichored petrichoring petrichorly
    petrichorred petrichorring petrichors pine pined pines pining pungent>3
    pungently>3 rancid>3 rancidder>3 ranciddest>3 rancider>3 rancidest>3
    rancidly>3 reek reeked reeking reeks resin resins rot roted roting rots
    rotted rotten rottener rottenest rottenly rottenner rottennest rotting sap
    saped saping sapped sapping saps scent scented scentedly scenting scents
    sewage sewages smell smelled smellier smelliest smellily smelling smells
    smelly smelt smokier>3 smokiest>3 smokily>3 smoky>3 sniff>5 sniffed>5
    sniffing>5 sniffs>5 soapier soapiest soapily soapy sootier sootiest
    sootily sooty sour>3 soured>3 sourer>3 sourest>3 souring>3 sourly>3
    sours>3 stale staled stalely staler stales stalest staling stank stench
    stenches stink stinked stinkier stinkiest stinkily stinking stinks stinky
    stunk sweet>3 sweeter>3 sweetest>3 sweetly>3 sweets>3 tang>3 tangs>3
    tarried tarrier tarries tarriest tarrily tarry tarrying vapor vapors
    vapour vapours waft wafted wafting wafts whiff whiffed whiffing whiffs`,
  // Taste
  `
    acid acidder aciddest acider acidest acidic acidicly acidities acidity
    acidly acids aftertaste aftertastes ate bit bite bited bites biting bitten
    bland blander blandest blandly bread breaded breading breads brine brined
    brines brining burnt burnter burntest burntly butter buttered buttering
    butterred butterring butters chalkier chalkiest chalkily chalky chew
    chewed chewier chewiest chewily chewing chews chewy cream creamed creamier
    creamiest creamily creaming creams creamy crisp crisped crisper crispest
    crisping crisply crisps drank drier>4 dries>4 driest>4 drily>4 drink
    drinked drinking drinks drunk dry>4 dryer>4 dryest>4 drying>4 eat eated
    eaten eating eats fizzier fizziest fizzily fizzy flavor flavored flavoring
    flavorred flavorring flavors flavour flavoured flavouring flavours
    fruitier fruitiest fruitily fruity gobble gobbled gobbles gobbling gulp
    gulped gulping gulps honey honeyed honeyer honeyest honeying honeyly
    honeys honeyyer honeyyest honied lemon>0 lemons>0 lick licked licking
    licks mellow mellowed mellower mellowest mellowing mellowly mellows
    mellowwer mellowwest metallic metallicly metallics milk milked milking
    milks mintier mintiest mintily minty mouthful mouthfuls nuttier nuttiest
    nuttily nutty oilier oiliest oilily oily raw rawer rawest rawly raws
    rawwer rawwest rich richer riches richest richly ripe ripely riper ripest
    salt salted salter saltest saltier saltiest saltily salting saltly salts
    salty savor savored savorier savories savoriest savorily savoring savorred
    savorring savors savory savourier savouries savouriest savourily savoury
    scrumptious scrumptiously sharp>4 sharper>4 sharpest>4 sharply>4 sharps>4
    sip siped siping sipped sipping sips slurp slurped slurping slurps
    smooth>4 smoothed>4 smoother>4 smoothest>4 smoothing>4 smoothly>4
    smooths>4 spice spiced spices spicier spiciest spicily spicing spicy suck
    sucked sucking sucks sugar sugared sugaring sugarred sugarring sugars swig
    swiged swigged swigging swiging swigs syrup syrups tangier tangiest
    tangily tangy tart tarter tartest tartly tarts taste tasted tasteless
    tastelessly tastes tastier tastiest tastily tasting tasty thick thicker
    thickest thickly thicks thin thined thiner thinest thining thinly thinned
    thinner thinnest thinning thins tinnier tinniest tinnily tinny tongue>5
    tongued>5 tongues>5 tonguing>5 vinegar vinegars waterier>4 wateriest>4
    waterily>4 watery>4 yeast yeasts yummier yummiest yummily yummy zest
    zested zesting zests`,
  // Touch
  `
    abrasive abrasively abrasives arid aridder ariddest arider aridest aridly
    ash ashed ashes ashing baked bakedly balm balms bark>1 barked>1 barking>1
    barks>1 bevel beveled beveling bevelled bevelling bevels blistering
    blisteringly blisterings brass brasses brick bricks bristle bristled
    bristles bristling brittle brittler brittles brittlest brittly brush>7
    brushed>7 brushes>7 brushing>7 bumpier bumpiest bumpily bumpy burlap
    burlaps burn>75 burned>75 burning>75 burns>75 chalk chalked chalking
    chalks chill>5 chilled>5 chilling>5 chills>5 clammier clammiest clammily
    clammy clay clays cloth cloths coarse coarsely coarser coarsest cold
    colder coldest coldly colds concrete concreted concretely concreter
    concretes concretest concreting cool cooled cooler coolest cooling coolly
    coolness coolnesses cools copper coppered coppering copperred copperring
    coppers corduroy corduroyed corduroying corduroys cotton cottoned
    cottoning cottonned cottonning cottons cracked crackedly crumb crumbed
    crumbing crumbs crushed crushedly dank danker dankest dankly denim denims
    dirt dirter dirtest dirtly dirts dried driedly dull>01 dulled>01 duller>01
    dullest>01 dulling>01 dullly>01 dulls>01 dust dusted dustier dustiest
    dustily dusting dusts dusty enamel enameled enameling enamelled enamelling
    enamels feather feathered feathering featherred featherring feathers feel
    feeled feeling feels felt fierier fieriest fierily fiery firm firmed
    firmer firmest firming firmly firms flat flater flatest flatly flatness
    flatnesses flats flatted flatter flattest flatting fluffier fluffiest
    fluffily fluffy foam foamed foaming foams freeze freezed freezes freezing
    frigid frigidder frigiddest frigider frigidest frigidly frost frosted
    frostier frostiest frostily frosting frosts frosty froze frozen fur furred
    furrier furriest furrily furring furry furs fuzzier fuzziest fuzzily fuzzy
    gauze gauzes glass glassed glasses glassier glassiest glassily glassing
    glassy grab>6 grabbed>6 grabbing>6 grabed>6 grabing>6 grabs>6 granite
    granites gravel graveled graveling gravelled gravelling gravels greasier
    greasiest greasily greasy grip griped griping gripped gripping grips gript
    grit grited griting grits gritted grittier grittiest grittily gritting
    gritty hard harder hardest hardly heat>5 heated heatedly heating>5 heats>5
    hot hoter hotest hotly hotter hottest humid humidder humiddest humider
    humidest humidities humidity humidly husk husked husking husks ice iced
    ices icier iciest icily icing icy iron ironed ironer ironest ironing
    ironly ironned ironner ironnest ironning irons jagged jaggedly lace laced
    laces lacing lacquer lacquered lacquering lacquers leather leathered
    leathering leatherred leatherring leathers limestone limestones linen
    linens marble marbled marbles marbling metal metaled metaling metalled
    metalling metally metals moist moister moistest moistly mud mudded muddied
    muddier muddies muddiest muddily mudding muddy muddying muded muding muds
    mushier mushiest mushily mushy numb numbed number numbest numbing numbly
    numbs overheated overheatedly padded paddedly paper papered papering
    paperred paperring papers parched parchedly pinch>7 pinched>7 pinches>7
    pinching>7 plaster plastered plastering plasterred plasterring plasters
    plastic plasticly plastics pointed pointedly polished polishedly press>67
    pressed>67 presses>67 pressing>67 pressure pressured pressures pressuring
    prick pricked pricking pricklier prickliest pricklily prickly pricks rind
    rinds rock>6 rocked>6 rockier rockiest rockily rocking>6 rocks>6 rocky
    rough roughed rougher roughest roughing roughly roughs rub rubbed rubber
    rubbered rubberer rubberest rubbering rubberly rubberred rubberrer
    rubberrest rubberring rubbers rubbing rubed rubing rubs rust rusted ruster
    rustest rusting rustly rusts sand sanded sanding sands satin satins
    scorched scorchedly scorching scorchingly scrape>71 scraped>71 scrapes>71
    scratch>7 scratched>7 scratches>7 scratchier scratchiest scratchily
    scratchy seam seamed seaming seams sharpened sharpenedly silk silkier>0
    silkiest>0 silkily>0 silks silky>0 sizzling sizzlingly slate slated slates
    slating slick slicked slicker slickest slicking slickly slicks slipperier
    slipperiest slipperily slippery soft>1 softer>1 softest>1 softly>1
    softness softnesses soggier>6 soggiest>6 soggily>6 soggy>6 solid solidder
    soliddest solider solidest solidly solids soot sooted sooting soots spiked
    spikedly splinter splintered splintering splinterred splinterring
    splinters squeeze squeezed squeezes squeezing squishier squishiest
    squishily squishy steamier steamiest steamily steaming steamingly steamy
    steel steeled steelier steeliest steelily steeling steels steely stickier
    stickiest stickily sticky sting>5 stinged>5 stinging>5 stings>5 stone
    stoned stonely stoner stones stonest stonier stoniest stonily stoning
    stony straw strawed strawer strawest strawing strawly straws strawwer
    strawwest stroke>6 stroked>6 strokes>6 stroking>6 stung>5 sultrier
    sultriest sultrily sultry surface>6 surfaced>6 surfacely>6 surfacer>6
    surfaces>6 surfacest>6 surfacing>6 tackier tackiest tackily tacky
    temperature>5 temperatures>5 tender tendered tenderer tenderest tendering
    tenderly tenderred tenderrer tenderrest tenderring tenders texture
    textures tile tiled tiles tiling tin tined tingle tingled tingles tingling
    tining tinned tinning tins touch touched touches touching tweed tweeds
    varnish varnished varnishes varnishing velvet velveter velvetest velvetier
    velvetiest velvetily velvetly velvets velvetter velvettest velvety warm
    warmed warmer warmest warming warmly warms water watered watering waterred
    waterring waters wax waxed waxes waxier waxiest waxily waxing waxy wet
    weted weter wetest weting wetly wets wetted wetter wettest wetting wood
    woodier woodiest woodily woods woody wool woollier woolliest woollily
    woolly wools`,
  // Organic
  `
    ache ached aches aching agonies agony ankle ankles arm armed arming arms
    arteries artery beard bearded bearding beards beat>7 beated>7 beaten>7
    beater>7 beatest>7 beating>7 beatly>7 beats>7 bellied bellies belly
    bellying blink blinked blinking blinks blister blistered blisterred
    blisterring blisters blood blooded blooding bloods bodied bodies body
    bodying bone boned bonely boner bones bonest boning brain brained braining
    brains breast breasted breasting breasts brow brows bruise bruised bruises
    bruising calli callus callused calluses callusing callussed callussing
    cheek cheeked cheeking cheeks chest chests chin chined chining chinned
    chinning chins choke choked chokes choking chokings clench clenched
    clenches clenching coldness coldnesses colic colics coughing coughings
    cramp cramped cramping cramps cried cries cry crying cryings dizzied
    dizzier dizzies dizziest dizzily dizzy dizzying ear ears elbow elbowed
    elbowing elbows exhaust exhausted exhausting exhausts eyebrow eyebrows
    eyelash eyelashes eyelid eyelids face faced faces facing faint fainted
    fainter faintest fainting faintly faints fat fated fater fatest fating
    fatly fats fatted fatter fattest fattier fatties fattiest fattily fatting
    fatty fever feverish feverishly fevers finger fingered fingering fingerred
    fingerring fingers fingertip fingertips flesh fleshed fleshes fleshing
    flinch>6 flinched>6 flinches>6 flinching>6 flush flusher flushes flushest
    flushing flushly forearm forearmed forearming forearms forehead foreheads
    freckle freckled freckles freckling gristle gristles gum gumed guming
    gummed gumming gums gut guted guting guts gutted gutting hair hairs hand
    handed handing hands head>6 headache headaches headed>6 heading>6 heads>6
    heart heartbeat heartbeats hearts heave heaved heaves heaving heel heeled
    heeling heels hiccup hiccuped hiccuping hiccupped hiccupping hiccups hip
    hiper hipest hiply hipper hippest hips hove hunger hungered hungering
    hungerred hungerring hungers hurting hurtings itch itched itches itching
    jaw jawed jawing jaws joint jointed jointer jointest jointing jointly
    joints knee knees knuckle knuckled knuckles knuckling lip lipped lipping
    lips liver liverer liverest liverly liverrer liverrest livers lump lumped
    lumping lumps lung lungs marrow marrows muscle muscled muscles muscling
    muscular muscularer muscularest muscularly muscularrer muscularrest nail>7
    nailed>7 nailing>7 nails>7 nausea nauseas neck necked necking necks nerve
    nerved nerves nerving numbness numbnesses pain pained paining pains palm
    palmed palming palms pang pangs pant panted panting pants pore pored pores
    poring puff puffed puffer puffest puffing puffly puffs pulse>6 pulsed>6
    pulses>6 pulsing>6 queasier queasiest queasily queasy retch retched
    retches retching rib ribbed ribbing ribed ribing ribs saliva salivas scab
    scabbed scabbing scabed scabing scabs scalp scalped scalping scalps scar
    scared scaring scarred scarring scars shin shinned shinning shins shiver
    shivered shivering shiverred shiverring shivers shoulder shouldered
    shouldering shoulderred shoulderring shoulders shudder shuddered
    shuddering shudderred shudderring shudders sinew sinews skeletal
    skeletally skeleton skeletons skin skined skining skinned skinning skins
    sneeze sneezed sneezes sneezing snore snored snores snoring snort snorted
    snorting snorts sole soled solely soler soles solest soling spat spine
    spines spit spited spiting spits spitted spitting stomach stomachache
    stomachaches stomached stomaches stomaching stubble stubbles suffering
    sufferingly sufferings swallow swallowed swallowing swallows sweat sweated
    sweating sweats swelling swellings tear>76 teared>76 tearing>76 tears>76
    teeth teeths temple temples tendon tendons thigh thighs thirst thirsted
    thirsting thirsts throat throats throb throbbed throbbing throbed throbing
    throbs thumb thumbed thumbing thumbs tire tired tiredly tires tiring
    tissue tissued tissues tissuing toe toed toes toing tooth toothache
    toothaches tooths tore>76 torn>76 tremble>6 trembled>6 trembles>6 vein
    veined veining veins waist waists warmth>4 warmths>4 wearied wearier
    wearies weariest wearily weary wearying wince winced winces wincing
    wrinkle wrinkled wrinkles wrinkling wrist wrists yawn yawned yawning yawns
    yelp>1 yelped>1 yelps>1`,
  // Kinesthetic
  `
    advance advanced advancely advancer advances advancest advancing approach
    approached approaches approaching ascend ascended ascending ascends
    backtrack backtracked backtracking backtracks balance balanced balances
    balancing barge barged barges barging bend bended bending bendings bends
    bent bob bobbed bobbing bobed bobing bobs bounce>7 bounced>7 bounces>7
    bouncier bounciest bouncily bouncing>7 bouncy brace braced braces bracing
    budge budged budges budging bustle bustled bustles bustling carried
    carries carry carrying cascade cascaded cascades cascading circle circled
    circles circling climb climbed climbing climbs coil coiled coiling coils
    cradle cradled cradles cradling crawl crawled crawling crawls creep
    creeped creeping creeps crept cross crossed crosser crosses crossest
    crossing crossly crouch crouched crouches crouching curl curled curling
    curls dance danced dances dancing dart darted darting darts dash dashed
    dashes dashing dawdle dawdled dawdles dawdling deflect deflected
    deflecting deflects depart departed departing departs descend descended
    descending descends deviate deviated deviately deviater deviates deviatest
    deviating dive dived dives diving dodge dodged dodges dodging dove drag
    draged dragged dragging draging drags dribble dribbled dribbles dribbling
    drift drifted drifting drifts drive drived driven drives driving drop
    droped droping dropped dropping drops drove duck ducked ducking ducks fall
    falled fallen falling falls falter faltered faltering falterred falterring
    falters flap flaped flaping flapped flapping flaps flew flied flier flies
    fliest flily flip fliped fliper flipest fliping fliply flipped flipper
    flippest flipping flips float floated floating floats flop floped floping
    flopped flopping flops flounder floundered floundering flounderred
    flounderring flounders flow flowed flowing flown flows flutter fluttered
    fluttering flutterred flutterring flutters fly flying fumble fumbled
    fumbles fumbling gallop galloped galloping gallopped gallopping gallops
    gesture gestured gestures gesturing glide glided glides gliding gravities
    gravity hang>7 hanged>7 hanging>7 hangs>7 hasten hastened hastening
    hastenned hastenning hastens haul hauled hauling hauls heavier heavies
    heaviest heavily heaviness heavinesses heavy hitch hitched hitches
    hitching hoist hoisted hoisting hoists hop hoped hoping hopped hopping
    hops hover hovered hovering hoverred hoverring hovers hung>7 hurried
    hurries hurry hurrying hustle hustled hustles hustling inch inched inches
    inching jerk jerked jerking jerks jolt jolted jolting jolts judder
    juddered juddering judderred judderring judders jump jumped jumping jumps
    kneel kneeled kneeling kneels knelt lean leaned leaner leanest leaning
    leanly leans leant leap leaped leaping leaps leapt lift lifted lifting
    lifts lightness lightnesses lightweight lightweightly lightweights limp
    limped limper limpest limping limpings limply limps loop looped looping
    loops loose loosed loosely looser looses loosest loosing lower lowered
    lowering lowerred lowerring lowers lumber lumbered lumbering lumberred
    lumberring lumbers lunge lunged lunges lunging lurch lurched lurches
    lurching march marched marches marching momenta momentum momentums motion
    motioned motioning motions move moved movement movements moves moving
    overtake overtaked overtaken overtakes overtaking overtook overturn
    overturned overturning overturns pace paced paces pacing perch perched
    perches perching pivot pivoted pivoting pivots pivotted pivotting plunge
    plunged plunges plunging poise poised poises poising posture postured
    postures posturing pounce pounced pounces pouncing pound pounded pounding
    pounds prance pranced prances prancing prop>7 proped>7 proping>7 propped>7
    propping>7 props>7 prowl prowled prowling prowls pull pulled pulling pulls
    push pushed pushes pushing quiver quivered quivering quiverred quiverring
    quivers race raced races racing raise raised raises raising ran reach
    reached reaches reaching rebound rebounded rebounding rebounds recline
    reclined reclines reclining recoil recoiled recoiling recoils reel reeled
    reeling reels resist resisted resisting resists rest rested resting rests
    retreat retreated retreating retreats return returned returning returns
    revolve revolved revolves revolving ridden ride rided rides riding ripple
    rippled ripples rippling rise rised risen rises rising roam roamed roaming
    roams rode roll rolled rolling rolls rose rotate rotated rotates rotating
    ruffle ruffled ruffles ruffling run runed runing runned running runs rush
    rushed rusher rushes rushest rushing rushly sank sat scatter scattered
    scattering scatterred scatterring scatters scoot scooted scooting scoots
    scramble scrambled scrambles scrambling scuff scuffed scuffing scuffs
    settle settled settles settling shake shaked shaken shakes shaking shift
    shifted shifting shifts shimmied shimmies shimmy shimmying shook shuffle
    shuffled shuffles shuffling sidle sidled sidles sidling sink sinked
    sinking sinks sit sited siting sits sitted sitting skim skimed skimer
    skimest skiming skimly skimmed skimmer skimmest skimming skims skip skiped
    skiping skipped skipping skips slack slacked slacker slackest slacking
    slackly slacks slid slidden slide slided slides sliding slink slinked
    slinking slinks slip sliped sliping slipped slipping slips slump slumped
    slumping slumps slunk sneak sneaked sneaker sneakest sneaking sneakly
    sneaks snuck soar soared soaring soars spill spilled spilling spills spilt
    spin spined spining spinned spinning spins spiral spiraled spiraling
    spiralled spiralling spirally spirals sprang sprawl sprawled sprawling
    sprawls spring springed springing springs sprung spun squirm squirmed
    squirming squirms stabilities stability stabilized stabilizedly stable
    stabled stabler stables stablest stabling stably stagger staggered
    staggering staggerred staggerring staggers stamp stamped stamping stamps
    stance stances stand standed standing stands steadied steadier steadies
    steadiest steadily steady steadying steal stealed stealing steals step
    steped steping stepped stepping steps stiff stiffer stiffest stiffly
    stiffs stole stolen stomp stomped stomping stomps stood streak streaked
    streaking streaks stream streamed streaming streams stretch stretched
    stretcher stretches stretchest stretching stretchly stroll strolled
    strolling strolls strut struted struting struts strutted strutting stumble
    stumbled stumbles stumbling sunk sunken surge surged surges surging
    swagger swaggered swaggerer swaggerest swaggering swaggerly swaggerred
    swaggerrer swaggerrest swaggerring swaggers swam sway swayed swaying sways
    swerve swerved swerves swerving swim swimed swiming swimmed swimming swims
    swing swinged swinging swings swirl swirled swirling swirls swivel
    swiveled swiveling swivelled swivelling swivels swoop swooped swooping
    swoops swum swung taut tauter tautest tautly teeter teetered teetering
    teeterred teeterring teeters tension tensions thrash thrashed thrashes
    thrashing thrust thrusted thrusting thrusts tight tighter tightest tightly
    tilt tilted tilting tilts tiptoe tiptoed tiptoely tiptoer tiptoes tiptoest
    tiptoing topple toppled topples toppling totter tottered tottering
    totterred totterring totters trail trailed trailing trails tramp tramped
    tramping trample trampled tramples tramps travel traveled traveling
    travelled travelling travels traverse traversed traverses traversing tread
    treaded treading treads trembling tremblingly tremblings tremor tremored
    tremoring tremorred tremorring tremors trickle trickled trickles trickling
    trip triped triping tripped tripping trips trod trodden tumble tumbled
    tumbles tumbling turn turned turning turns twitch twitched twitches
    twitching twitchings unsteadied unsteadier unsteadiest unsteadily unsteady
    upright uprighter uprightest uprightly uprights veer veered veering veers
    wade waded wades wading walk walked walking walks wander wandered
    wandering wanderred wanderring wanders wave waved waver wavered wavering
    waverred waverring wavers waves waving weigh weighed weighing weighs
    weight weighted weighting weightless weightlessly weights wheel wheeled
    wheeling wheels whirl whirled whirling whirls wiggle wiggled wiggles
    wiggling withdraw withdrawed withdrawing withdrawn withdraws withdrew
    wobble wobbled wobbles wobbling wrench wrenched wrenches wrenching wriggle
    wriggled wriggles wriggling zigzag zigzaged zigzager zigzagest zigzagged
    zigzagger zigzaggest zigzagging zigzaging zigzagly zigzags`,
  // Physical
  `
    bind binded binding binds bolt>6 bolted>6 bolting>6 bolts>6 break breaked
    breaking breaks broke broken buckle buckled buckles buckling buried buries
    bury burying bust busted buster bustest busting bustly busts carve carved
    carves carving chip chiped chiping chipped chipping chips chop choped
    choping chopped chopping chops clamp clamped clamping clamps clinch
    clinched clinches clinching clip cliped cliping clipped clipping clips
    close closed closely closer closes closest closing crease creased creases
    creasing crumple crumpled crumples crumpling crush crushes crushing cut>6
    cuted>6 cuter>6 cutest>6 cuting>6 cutly>6 cuts>6 cutted>6 cutter>6
    cuttest>6 cutting>6 daub daubed daubing daubs dent dented denting dents
    dig diged digged digging diging digs dip diped diping dipped dipping dips
    drill drilled drilling drills dug emptied emptier empties emptiest emptily
    empty emptying fasten fastened fastening fastenned fastenning fastens fill
    filled filling fills flatten flattened flattening flattenned flattenning
    flattens fling>6 flinged>6 flinging>6 flings>6 flung>6 fold folded folding
    folds gash gashed gashes gashing glue glued glues gluing grind grinded
    grinds hack hacked hacking hacks hammer hammered hammering hammerred
    hammerring hammers held hit hited hiting hits hitted hitting hold holded
    holding holds hook hooked hooking hooks hurl>6 hurled>6 hurling>6 hurls>6
    kick>6 kicked>6 kicking>6 kicks>6 knead kneaded kneading kneads knot
    knoted knoting knots knotted knotting latch latched latches latching lock
    locked locking locks lodge lodged lodges lodging loosen loosened loosening
    loosenned loosenning loosens mash mashed mashes mashing notch notched
    notches notching nudge nudged nudges nudging open opened opener openest
    opening openly openned openner opennest openning opens padlock padlocked
    padlocking padlocks paste pasted pastes pasting peel peeled peeling peels
    pile piled piles piling pin pinned pinning pins plug pluged plugged
    plugging pluging plugs poke poked pokes poking polish>04 polishes>04
    polishing>04 polishly>04 pour poured pouring pours prod prodded prodding
    proded proding prods pump pumped pumping pumps punch punched punches
    punching rap raped raping rapped rapping raps rinse rinsed rinses rinsing
    rip riped riping ripped ripping rips saw sawed sawing sawn saws scoop
    scooped scooping scoops scour scoured scouring scours screw screwed
    screwing screws scrub scrubbed scrubber scrubbest scrubbing scrubed
    scruber scrubest scrubing scrubly scrubs sculpt sculpted sculpting sculpts
    secure secured securely securer secures securest securing sever severed
    severing severred severring severs sew sewed sewing sewn sews shove shoved
    shovel shoveled shoveling shovelled shovelling shovels shoves shoving
    shred shredded shredding shreded shreding shreds shut shuted shuter
    shutest shuting shutly shuts shutted shutter shuttest shutting sift>6
    sifted>6 sifting>6 sifts>6 slap slaped slaping slapped slapping slaps
    slash slashed slashes slashing slice sliced slices slicing slit slited
    sliting slits slitted slitting smear smeared smearing smears soak soaked
    soaking soaks split splited spliter splitest spliting splitly splits
    splitted splitter splittest splitting spread spreaded spreader spreadest
    spreading spreadly spreads squash squashed squashes squashing stack
    stacked stacking stacks staple stapled stapler staples staplest stapling
    staply stick sticked sticking sticks stir>6 stired>6 stiring>6 stirred>6
    stirring>6 stirs>6 stitch stitched stitches stitching strain strained
    straining strains strap straped straping strapped strapping straps strike
    striked strikes striking strip stripped stripping strips struck stuck
    sweep>6 sweeped>6 sweeping>6 sweeps>6 swept>6 threw>6 throw>6 throwed>6
    throwing>6 thrown>6 throws>6 tie tied ties tighten tightened tightening
    tightenned tightenning tightens tiing toss>6 tossed>6 tosses>6 tossing>6
    trim trimed trimer trimest triming trimly trimmed trimmer trimmest
    trimming trims tuck tucked tucking tucks twist>6 twisted>6 twisting>6
    twists>6 tying unlock unlocked unlocking unlocks unscrew unscrewed
    unscrewing unscrews unwrap unwraped unwraping unwrapped unwrapping unwraps
    wash washed washes washing weave weaved weaves weaving wedge wedged wedges
    wedging whisk whisked whisking whisks wipe wiped wipes wiping wire wired
    wires wiring wove woven wrap wraped wraping wrapped wrapping wraps wring
    wringed wringing wrings wrung zip ziped ziping zipped zipping zips`,
];

/**
 * Abstract verbs — become, seem, consider, exist. Deliberately *not* a sense:
 * they are the opposite of what object writing is for, so they are counted and
 * reported as a flag rather than scored as sensory writing. Any word a sense
 * claims is absent here; the senses win.
 */
const PACKED_ABSTRACT = `
  allow allowed allowing allows applied applies apply applying argue argued
  argues arguing arrive arrived arrives arriving ask asked asking asks
  assume assumed assumes assuming attempt attempted attempting attempts
  avoid avoided avoiding avoids became become becomed becomes becoming began
  begin begined begining beginned beginning begins begun believe believed
  believes believing belong belonged belonging belongs bought bring bringed
  bringing brings brought build builded building builds built buy buyed
  buying buys call called calling calls cause caused causes causing change
  changed changes changing choose choosed chooses choosing chose chosen
  claim claimed claiming claims comed comes coming compare compared compares
  comparing complete completed completes completing concerned concerning
  concerns confirm confirmed confirming confirms connect connected
  connecting connects consider considered considering considerred
  considerring considers consist consisted consisting consists contain
  contained containing contains continue continued continues continuing
  create created creates creating deal dealed dealing deals dealt decide
  decided decides deciding depend depended depending depends describe
  described describes describing deserve deserved deserves deserving
  determine determined determines determining develop developed developing
  developped developping develops die died dies diing discover discovered
  discovering discoverred discoverring discovers discuss discussed discusses
  discussing divide divided divides dividing doed doing done dos dying earn
  earned earning earns encourage encouraged encourages encouraging end ended
  ending ends enjoy enjoyed enjoying enjoys ensure ensured ensures ensuring
  enter entered enterred enterring enters establish established establishes
  establishing examine examined examines examining exchange exchanged
  exchanges exchanging exist existed existing exists expand expanded
  expanding expands expect expected expecting expects explain explained
  explaining explains express expressed expresses expressing extend extended
  extending extends fail failed failing fails fight fighted fighting fights
  find finded finding finds fixed fixes fixing followed following follows
  forget forgeted forgeting forgets forgetted forgetting forgot forgotten
  fought found gain gained gaining gains gave geted geting gets getted
  getting give gived given gives giving goed goes going gone gos gotten grew
  grow growed growing grown grows guess guessed guesses guessing happen
  happened happening happenned happenning happens hate hated hates hating
  haved haves having help helped helping helps identified identifies
  identify identifying imagine imagined imagines imagining improve improved
  improves improving include included includes including indicate indicated
  indicates indicating inform informed informing informs intend intended
  intending intends introduce introduced introduces introducing involve
  involved involves involving judge judged judges judging justified
  justifies justify justifying keep keeped keeping keeps kept kill killed
  killing kills knew knowed knowing known knows lead leaded leading leads
  learn learned learning learns learnt leave leaved leaves leaving led left
  lend lended lending lends lent let leted leting lets letted letting live
  lived lives living lose losed loses losing lost made make maked makes
  making manage managed manages managing mean meaned meaning means meant
  meet meeted meeting meets mention mentioned mentioning mentions met miss
  missed misses missing need needed needing needs obtain obtained obtaining
  obtains occur occured occuring occurred occurring occurs paid passed
  passes passing pay payed paying pays perform performed performing performs
  permit permited permiting permits permitted permitting persuade persuaded
  persuades persuading possess possessed possesses possessing prefer
  prefered prefering preferred preferring prefers prepare prepared prepares
  preparing prevent prevented preventing prevents produce produced produces
  producing propose proposed proposes proposing protect protected protecting
  protects prove proved proven proves provide provided provides providing
  proving publish published publishes publishing put puted puting puts
  putted putting read readed reading reads realise realised realises
  realising realize realized realizes realizing reckon reckoned reckoning
  reckonned reckonning reckons recognise recognised recognises recognising
  recognize recognized recognizes recognizing recommend recommended
  recommending recommends reduce reduced reduces reducing refered refering
  referred referring refers refuse refused refuses refusing regarded
  regarding regards reject rejected rejecting rejects related relates
  relating relied relies rely relying remain remained remaining remains
  remember remembered remembering rememberred rememberring remembers remove
  removed removes removing repeat repeated repeating repeats replace
  replaced replaces replacing replied replies reply replying represent
  represented representing represents require required requires requiring
  respond responded responding responds reveal revealed revealing reveals
  said satisfied satisfies satisfy satisfying save saved saves saving say
  sayed saying says seek seeked seeking seeks seem seemed seeming seems
  select selected selecting selects sell selled selling sells send sended
  sending sends sent separate separated separates separating serve served
  serves serving show showed showing shown shows sold solve solved solves
  solving sought speak speaked speaking speaks spend spended spending spends
  spent spoke spoken start started starting starts stay stayed staying stays
  stop stoped stoping stopped stopping stops succeed succeeded succeeding
  succeeds suffer suffered sufferred sufferring suffers suggest suggested
  suggesting suggests supplied supplies supply supplying support supported
  supporting supports suppose supposed supposes supposing survive survived
  survives surviving take taked taken takes taking taught teach teached
  teaches teaching tell telled telling tells tend tended tending tends thank
  thanked thanking thanks think thinked thinking thinks thought told took
  tried tries try trying understand understanded understanding understands
  understood use used uses using varied varies vary varying visit visited
  visiting visits visitted visitting vote voted votes voting wait waited
  waiting waits want wanted wanting wants warn warned warning warns wear
  weared wearing wears welcome welcomed welcomes welcoming win wined wining
  winned winning wins wish wished wishes wishing won wonder wondered
  wondering wonderred wonderring wonders wore worn worried worries worry
  worrying write writed writes writing written wrote`;

export interface SenseEntry {
  primary: number;
  secondary: number[];
}

function unpack(): Map<string, SenseEntry> {
  const map = new Map<string, SenseEntry>();
  PACKED.forEach((group, primary) => {
    for (const token of group.split(/\s+/)) {
      if (!token) continue;
      const cut = token.indexOf(">");
      if (cut === -1) map.set(token, { primary, secondary: [] });
      else map.set(token.slice(0, cut), {
        primary,
        secondary: [...token.slice(cut + 1)].map(Number),
      });
    }
  });
  return map;
}

/** Inflected form → its primary sense and any secondaries. */
export const SENSE_INDEX: Map<string, SenseEntry> = unpack();

export const ABSTRACT_VERBS: Set<string> = new Set(
  PACKED_ABSTRACT.split(/\s+/).filter(Boolean),
);

export const ALL_SENSE_WORDS: Set<string> = new Set(SENSE_INDEX.keys());
